# Generated by Django 3.2.9 on 2022-02-08 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220204_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='tower',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='towers', to=settings.AUTH_USER_MODEL),
        ),
    ]
