# Generated by Django 3.2.9 on 2022-02-11 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tower_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date_dued',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='date_dued',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='expenseclaim',
            name='date_dued',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_dued',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
